language: python
sudo: false

python:
  - 3.5
  - 2.7

before_install:
  - export PATH="$HOME/.cask/bin:$HOME/.evm/bin:$PATH"

  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

  - curl -fsSkL https://github.com/cask/cask/raw/master/go | python

  - pip install ipython

env:
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  fast_finish: true
  allow_failures:
    env:
      - EVM_EMACS=emacs-git-snapshot-travis

install:
  - sed -i "s/^(source \"\([^\"]*\)\" .*)/(source \1)/" Cask
  - rm -rf $HOME/.emacs.d
  - ln -s $PWD $HOME/.emacs.d

before_script:
  - cask

script:
  - ./.travis-build.sh
