language: emacs-lisp

before_install:
  - export PATH="$HOME/.cask/bin:$HOME/.evm/bin:$PATH"

  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

  - curl -fsSkL https://github.com/cask/cask/raw/master/go | python

env:
  # - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  # - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  allow_failures:
    env:
      - EVM_EMACS=emacs-git-snapshot-travis

before_script:
  - lsb_release -a
  - emacs -Q --version
  - cask install

script:
  - ./.travis-build.sh
