language: emacs-lisp
sudo: false

before_install:
  - export PATH="$HOME/.cask/bin:$HOME/.evm/bin:$PATH"

  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

  - curl -fsSkL https://github.com/cask/cask/raw/master/go | python

env:
  # - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  # - EVM_EMACS=emacs-git-snapshot-travis

matrix:
  fast_finish: true
  allow_failures:
    env:
      - EVM_EMACS=emacs-git-snapshot-travis

before_script:
  - if [ -d $HOME/.emacs.d ]; then rm -rf $HOME/.emacs.d; fi
  - ln -s $PWD $HOME/.emacs.d
  - cask

script:
  - ./.travis-build.sh
